import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from storm.utils import load_joblib


def _parse_args():
    parser = argparse.ArgumentParser(
        description="Visualize latent factors saved in state.joblib."
    )
    parser.add_argument(
        "--state",
        required=True,
        help="Path to state.joblib generated by DynamicSingleVQVAETrainer.state().",
    )
    parser.add_argument(
        "--outdir",
        default=None,
        help="Optional output directory. Defaults to <state_dir>/state_plots.",
    )
    parser.add_argument(
        "--max-heatmap-dim",
        type=int,
        default=64,
        help="Maximum number of factor dimensions to display in the heatmap.",
    )
    parser.add_argument(
        "--annotate-every",
        type=int,
        default=20,
        help="Annotate every N-th timestamp on the x-axis.",
    )
    return parser.parse_args()


def _extract_factors(state_obj):
    items = state_obj.get("items", {})
    if not items:
        raise ValueError("No factor items found in state.joblib.")

    timestamps = list(items.keys())
    factors = []
    for timestamp in timestamps:
        factor = np.asarray(items[timestamp]["factor"], dtype=np.float64)
        factors.append(factor.reshape(-1))

    factor_matrix = np.stack(factors, axis=0)
    return timestamps, factor_matrix


def _pca_2d(x: np.ndarray):
    centered = x - x.mean(axis=0, keepdims=True)
    _u, s, vt = np.linalg.svd(centered, full_matrices=False)
    coords = centered @ vt[:2].T

    total_var = np.sum(s ** 2)
    if total_var <= 0:
        explained = np.array([0.0, 0.0], dtype=np.float64)
    else:
        explained = (s[:2] ** 2) / total_var
    return coords, explained


def _plot_pca(timestamps, factors, out_path: Path):
    coords, explained = _pca_2d(factors)

    fig, ax = plt.subplots(figsize=(10, 8))
    scatter = ax.scatter(
        coords[:, 0],
        coords[:, 1],
        c=np.arange(len(timestamps)),
        cmap="viridis",
        s=30,
        alpha=0.85,
    )
    ax.set_title("Latent Factors PCA Projection")
    ax.set_xlabel(f"PC1 ({explained[0] * 100:.2f}% var)")
    ax.set_ylabel(f"PC2 ({explained[1] * 100:.2f}% var)")

    if len(timestamps) <= 20:
        for i, ts in enumerate(timestamps):
            ax.annotate(ts, (coords[i, 0], coords[i, 1]), fontsize=8, alpha=0.7)

    cbar = fig.colorbar(scatter, ax=ax)
    cbar.set_label("Time Order")

    fig.tight_layout()
    fig.savefig(out_path, dpi=200)
    plt.close(fig)


def _plot_heatmap(timestamps, factors, out_path: Path, max_heatmap_dim: int, annotate_every: int):
    n_dims = min(factors.shape[1], max_heatmap_dim)
    data = factors[:, :n_dims].T

    fig_width = max(12, len(timestamps) * 0.08)
    fig_height = max(6, n_dims * 0.18)
    fig, ax = plt.subplots(figsize=(fig_width, fig_height))

    im = ax.imshow(data, aspect="auto", cmap="coolwarm")
    ax.set_title(f"Latent Factor Heatmap (first {n_dims} dims)")
    ax.set_ylabel("Factor Dimension")
    ax.set_xlabel("Timestamp")

    if annotate_every > 0:
        tick_positions = list(range(0, len(timestamps), annotate_every))
        if tick_positions and tick_positions[-1] != len(timestamps) - 1:
            tick_positions.append(len(timestamps) - 1)
        elif not tick_positions:
            tick_positions = [len(timestamps) - 1]
        ax.set_xticks(tick_positions)
        ax.set_xticklabels([timestamps[i] for i in tick_positions], rotation=45, ha="right")

    fig.colorbar(im, ax=ax, label="Factor Value")
    fig.tight_layout()
    fig.savefig(out_path, dpi=200)
    plt.close(fig)


def _save_summary(meta, timestamps, factors, out_path: Path):
    summary_lines = [
        f"num_timestamps: {len(timestamps)}",
        f"factor_matrix_shape: {tuple(factors.shape)}",
    ]
    if meta:
        for key, value in meta.items():
            summary_lines.append(f"{key}: {value}")

    summary_lines.extend(
        [
            f"factor_mean_abs: {float(np.mean(np.abs(factors))):.6f}",
            f"factor_std: {float(np.std(factors)):.6f}",
            f"factor_min: {float(np.min(factors)):.6f}",
            f"factor_max: {float(np.max(factors)):.6f}",
        ]
    )

    out_path.write_text("\n".join(summary_lines), encoding="utf-8")


def main():
    args = _parse_args()

    state_path = Path(args.state).resolve()
    if not state_path.exists():
        raise FileNotFoundError(f"state.joblib not found: {state_path}")

    outdir = Path(args.outdir).resolve() if args.outdir else state_path.parent / "state_plots"
    outdir.mkdir(parents=True, exist_ok=True)

    state_obj = load_joblib(str(state_path))
    meta = state_obj.get("meta", {})
    timestamps, factors = _extract_factors(state_obj)

    _plot_pca(timestamps, factors, outdir / "latent_factors_pca.png")
    _plot_heatmap(
        timestamps,
        factors,
        outdir / "latent_factors_heatmap.png",
        max_heatmap_dim=args.max_heatmap_dim,
        annotate_every=args.annotate_every,
    )
    _save_summary(meta, timestamps, factors, outdir / "summary.txt")

    print(f"Saved plots to: {outdir}")
    print(f"factor_matrix_shape: {factors.shape}")


if __name__ == "__main__":
    main()
