import argparse
import json
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import torch

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from storm.utils import load_joblib


def _parse_args():
    parser = argparse.ArgumentParser(
        description="Plot sampled latent factors and VQ codebook embeddings in one PCA space."
    )
    parser.add_argument(
        "--state",
        required=True,
        help="Path to state.joblib generated by DynamicSingleVQVAETrainer.state().",
    )
    parser.add_argument(
        "--checkpoint",
        default=None,
        help="Checkpoint path. If omitted, try <state_dir>/checkpoint/best.pth.",
    )
    parser.add_argument(
        "--outdir",
        default=None,
        help="Output directory. Defaults to <state_dir>/state_plots.",
    )
    parser.add_argument(
        "--factor-part",
        choices=["auto", "quantized", "encoder", "full"],
        default="auto",
        help=(
            "Which part of saved factors to compare with the codebook. "
            "For concat factors [encoder, quantized], auto uses quantized."
        ),
    )
    parser.add_argument(
        "--num-factor-samples",
        type=int,
        default=8000,
        help="Number of latent factor tokens to sample for the scatter plot.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=2026,
        help="Random seed for factor token sampling.",
    )
    parser.add_argument(
        "--annotate-top-k",
        type=int,
        default=8,
        help="Annotate the top-K most frequently used codebook entries.",
    )
    parser.add_argument(
        "--codebook-size",
        type=int,
        default=None,
        help="Expected codebook size. Defaults to the size loaded from checkpoint.",
    )
    return parser.parse_args()


def _find_checkpoint(state_path: Path, checkpoint_arg: str | None):
    if checkpoint_arg:
        checkpoint_path = Path(checkpoint_arg).resolve()
        if not checkpoint_path.exists():
            raise FileNotFoundError(f"checkpoint not found: {checkpoint_path}")
        return checkpoint_path

    candidates = [
        state_path.parent / "checkpoint" / "best.pth",
        state_path.parent / "checkpoints" / "best.pth",
        state_path.parent / "best.pth",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate.resolve()

    checkpoint_dir = state_path.parent / "checkpoint"
    if checkpoint_dir.exists():
        checkpoint_files = sorted(checkpoint_dir.glob("*.pth"), key=lambda p: p.stat().st_mtime)
        if checkpoint_files:
            return checkpoint_files[-1].resolve()

    raise FileNotFoundError(
        "Could not find checkpoint automatically. Pass --checkpoint explicitly."
    )


def _load_codebook(checkpoint_path: Path):
    payload = torch.load(str(checkpoint_path), map_location="cpu")
    model_state = payload.get("model_state", payload) if isinstance(payload, dict) else payload

    preferred_keys = [
        "quantizer._codebook.embed",
        "module.quantizer._codebook.embed",
    ]
    for key in preferred_keys:
        if key in model_state:
            tensor = model_state[key]
            break
    else:
        matches = [
            key
            for key in model_state.keys()
            if key.endswith("quantizer._codebook.embed") or key.endswith("_codebook.embed")
        ]
        if not matches:
            raise KeyError(
                "Could not find codebook embedding in checkpoint. "
                "Expected a key like 'quantizer._codebook.embed'."
            )
        key = sorted(matches, key=len)[0]
        tensor = model_state[key]

    codebook = tensor.detach().cpu().float().numpy()
    if codebook.ndim == 3 and codebook.shape[0] == 1:
        codebook = codebook[0]
    elif codebook.ndim == 3:
        codebook = codebook.reshape(-1, codebook.shape[-1])
    elif codebook.ndim != 2:
        raise ValueError(f"Unsupported codebook shape from {key}: {codebook.shape}")

    return codebook, key


def _extract_factor_tokens(state_obj, codebook_dim: int, factor_part: str):
    items = state_obj.get("items", {})
    if not items:
        raise ValueError("No factor items found in state.joblib.")

    timestamps = list(items.keys())
    factors = []
    for timestamp in timestamps:
        factor = np.asarray(items[timestamp]["factor"], dtype=np.float32)
        factors.append(factor.reshape(-1, factor.shape[-1]))

    tokens = np.concatenate(factors, axis=0)
    factor_dim = tokens.shape[-1]

    resolved_part = factor_part
    if factor_part == "auto":
        resolved_part = "full" if factor_dim == codebook_dim else "quantized"

    if resolved_part == "full":
        if factor_dim != codebook_dim:
            raise ValueError(
                f"Cannot compare full factor dim {factor_dim} with codebook dim {codebook_dim}. "
                "Use --factor-part quantized or --factor-part encoder."
            )
        selected = tokens
    elif resolved_part == "quantized":
        if factor_dim == codebook_dim:
            selected = tokens
        elif factor_dim == codebook_dim * 2:
            selected = tokens[:, codebook_dim:]
        else:
            raise ValueError(
                f"Cannot infer quantized half from factor dim {factor_dim} and codebook dim {codebook_dim}."
            )
    elif resolved_part == "encoder":
        if factor_dim == codebook_dim:
            selected = tokens
        elif factor_dim == codebook_dim * 2:
            selected = tokens[:, :codebook_dim]
        else:
            raise ValueError(
                f"Cannot infer encoder half from factor dim {factor_dim} and codebook dim {codebook_dim}."
            )
    else:
        raise ValueError(f"Unsupported factor part: {factor_part}")

    return timestamps, tokens, selected.astype(np.float32, copy=False), resolved_part


def _normalize_count_items(count_obj):
    if count_obj is None:
        return {}

    if isinstance(count_obj, dict) and "count" in count_obj:
        count_obj = count_obj["count"]

    normalized = {}
    for key, value in dict(count_obj).items():
        try:
            idx = int(key)
        except (TypeError, ValueError):
            continue
        normalized[idx] = int(value)
    return normalized


def _load_code_counts(state_obj, state_path: Path, codebook_size: int):
    counts = _normalize_count_items(state_obj.get("count"))
    if not counts:
        count_path = state_path.parent / "count.json"
        if count_path.exists():
            with count_path.open("r", encoding="utf-8") as f:
                counts = _normalize_count_items(json.load(f))

    usage = np.zeros(codebook_size, dtype=np.float64)
    for idx, value in counts.items():
        if 0 <= idx < codebook_size:
            usage[idx] = float(value)
    return usage


def _sample_rows(x: np.ndarray, num_samples: int, seed: int):
    if num_samples <= 0 or num_samples >= x.shape[0]:
        return x
    rng = np.random.default_rng(seed)
    indices = rng.choice(x.shape[0], size=num_samples, replace=False)
    return x[indices]


def _fit_pca_transform(x: np.ndarray):
    mean = x.mean(axis=0, keepdims=True)
    std = x.std(axis=0, keepdims=True)
    std[std < 1e-8] = 1.0
    normalized = (x - mean) / std

    _u, s, vt = np.linalg.svd(normalized, full_matrices=False)
    total_var = float(np.sum(s ** 2))
    explained = (s[:2] ** 2) / total_var if total_var > 0 else np.zeros(2, dtype=np.float64)

    def transform(values: np.ndarray):
        return ((values - mean) / std) @ vt[:2].T

    return transform, explained


def _plot_latent_codebook(
    factor_points: np.ndarray,
    codebook: np.ndarray,
    usage: np.ndarray,
    out_path: Path,
    factor_part: str,
    annotate_top_k: int,
):
    combined = np.concatenate([factor_points, codebook], axis=0)
    transform, explained = _fit_pca_transform(combined)
    factor_xy = transform(factor_points)
    codebook_xy = transform(codebook)

    total_usage = usage.sum()
    usage_pct = usage / total_usage * 100.0 if total_usage > 0 else usage
    max_pct = float(usage_pct.max()) if usage_pct.size else 0.0
    size_scale = np.sqrt(usage_pct / max(max_pct, 1e-12))
    marker_sizes = 55.0 + 360.0 * size_scale

    fig, ax = plt.subplots(figsize=(11, 9))
    ax.scatter(
        factor_xy[:, 0],
        factor_xy[:, 1],
        s=8,
        color="#86b6e8",
        alpha=0.16,
        linewidths=0,
        label=f"Latent factors ({factor_part}, sampled)",
    )

    scatter = ax.scatter(
        codebook_xy[:, 0],
        codebook_xy[:, 1],
        c=usage_pct,
        s=marker_sizes,
        cmap="Reds",
        marker="D",
        edgecolors="#111827",
        linewidths=0.45,
        alpha=0.92,
        label="Codebook embeddings",
        zorder=3,
    )

    if annotate_top_k > 0 and usage_pct.size:
        top_indices = np.argsort(usage_pct)[::-1][:annotate_top_k]
        for idx in top_indices:
            ax.annotate(
                str(idx),
                (codebook_xy[idx, 0], codebook_xy[idx, 1]),
                xytext=(5, 5),
                textcoords="offset points",
                fontsize=8,
                color="#991b1b",
                weight="bold",
            )

    ax.set_title("Latent Factors and Codebook Embeddings (PCA)")
    ax.set_xlabel(f"PC1 ({explained[0] * 100:.2f}% var)")
    ax.set_ylabel(f"PC2 ({explained[1] * 100:.2f}% var)")
    ax.grid(True, linestyle="--", linewidth=0.6, alpha=0.22)
    ax.legend(loc="best", frameon=True)

    cbar = fig.colorbar(scatter, ax=ax, pad=0.015)
    cbar.set_label("Code usage (%)")

    fig.tight_layout()
    fig.savefig(out_path, dpi=240)
    plt.close(fig)

    return {
        "pc1_var": float(explained[0]),
        "pc2_var": float(explained[1]),
        "max_usage_pct": max_pct,
        "top_code_indices": np.argsort(usage_pct)[::-1][: max(annotate_top_k, 1)].tolist(),
    }


def _save_summary(
    out_path: Path,
    state_path: Path,
    checkpoint_path: Path,
    codebook_key: str,
    raw_tokens: np.ndarray,
    selected_tokens: np.ndarray,
    sampled_tokens: np.ndarray,
    codebook: np.ndarray,
    usage: np.ndarray,
    factor_part: str,
    plot_stats: dict,
):
    used = int(np.sum(usage > 0))
    dead = int(np.sum(usage == 0))
    total = int(np.sum(usage))
    usage_pct = usage / usage.sum() * 100.0 if usage.sum() > 0 else usage

    lines = [
        f"state: {state_path}",
        f"checkpoint: {checkpoint_path}",
        f"codebook_key: {codebook_key}",
        f"raw_factor_tokens_shape: {tuple(raw_tokens.shape)}",
        f"selected_factor_tokens_shape: {tuple(selected_tokens.shape)}",
        f"sampled_factor_tokens_shape: {tuple(sampled_tokens.shape)}",
        f"factor_part: {factor_part}",
        f"codebook_shape: {tuple(codebook.shape)}",
        f"codebook_used: {used}/{len(usage)}",
        f"dead_codes: {dead}",
        f"total_code_tokens: {total}",
        f"max_usage_pct: {float(np.max(usage_pct)) if usage_pct.size else 0.0:.6f}",
        f"pc1_var: {plot_stats['pc1_var']:.6f}",
        f"pc2_var: {plot_stats['pc2_var']:.6f}",
        f"top_code_indices: {plot_stats['top_code_indices']}",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main():
    args = _parse_args()

    state_path = Path(args.state).resolve()
    if not state_path.exists():
        raise FileNotFoundError(f"state.joblib not found: {state_path}")

    checkpoint_path = _find_checkpoint(state_path, args.checkpoint)
    outdir = Path(args.outdir).resolve() if args.outdir else state_path.parent / "state_plots"
    outdir.mkdir(parents=True, exist_ok=True)

    state_obj = load_joblib(str(state_path))
    codebook, codebook_key = _load_codebook(checkpoint_path)
    codebook_size, codebook_dim = codebook.shape
    if args.codebook_size is not None and args.codebook_size != codebook_size:
        raise ValueError(
            f"--codebook-size={args.codebook_size} but checkpoint codebook has size {codebook_size}."
        )

    _timestamps, raw_tokens, selected_tokens, factor_part = _extract_factor_tokens(
        state_obj,
        codebook_dim=codebook_dim,
        factor_part=args.factor_part,
    )
    sampled_tokens = _sample_rows(selected_tokens, args.num_factor_samples, args.seed)
    usage = _load_code_counts(state_obj, state_path, codebook_size)

    plot_stats = _plot_latent_codebook(
        sampled_tokens,
        codebook,
        usage,
        outdir / "latent_factors_codebook_pca.png",
        factor_part=factor_part,
        annotate_top_k=args.annotate_top_k,
    )
    _save_summary(
        outdir / "latent_factors_codebook_summary.txt",
        state_path=state_path,
        checkpoint_path=checkpoint_path,
        codebook_key=codebook_key,
        raw_tokens=raw_tokens,
        selected_tokens=selected_tokens,
        sampled_tokens=sampled_tokens,
        codebook=codebook,
        usage=usage,
        factor_part=factor_part,
        plot_stats=plot_stats,
    )

    print(f"Saved plot to: {outdir / 'latent_factors_codebook_pca.png'}")
    print(f"Saved summary to: {outdir / 'latent_factors_codebook_summary.txt'}")
    print(f"factor_part: {factor_part}")
    print(f"raw_factor_tokens_shape: {raw_tokens.shape}")
    print(f"selected_factor_tokens_shape: {selected_tokens.shape}")
    print(f"codebook_shape: {codebook.shape}")


if __name__ == "__main__":
    main()
